# Generated by Django 6.0.4 on 2026-05-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_center_course_centers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CenterPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.center')),
            ],
        ),
    ]
